// Code generated by raindrop build, DO NOT EDIT.
import { Ai, Annotation, App, KvCache, Logger, MRNObject, Tracer } from '@liquidmetal-ai/raindrop-framework';
import CourseService from '../course-api';

export interface Env {
  _raindrop: {
    app: App;
  };
  AI: Ai;
  annotation: Annotation<Omit<MRNObject, 'type' | 'applicationName' | 'versionId'>>;
  logger: Logger;
  mem: KvCache;
  tracer: Tracer;
  COURSE_SERVICE: CourseService;
  ELEVENLABS_API_KEY: string; // ElevenLabs API key for conversational AI
  ANTHROPIC_API_KEY: string; // Anthropic API key for slide generation
}
